name: Build Android APK

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main # 当你推送到 main 分支时自动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 安装 Android SDK
      uses: android-actions/setup-android@v3

    - name: 赋予 gradlew 执行权限
      run: chmod +x ./gradlew

    - name: 编译 Debug APK
      run: ./gradlew assembleDebug

    - name: 上传 APK 供下载
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
