
name: Android Debug APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Gradle 8.5
        run: |
          curl -sL https://services.gradle.org/distributions/gradle-8.5-bin.zip -o gradle.zip
          unzip -q gradle.zip
          echo "$GITHUB_WORKSPACE/gradle-8.5/bin" >> $GITHUB_PATH

      - name: Build Debug APK
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # --- Release signing (optional) ---
      # - name: Decode keystore
      #   if: ${{ secrets.KEYSTORE_BASE64 != '' }}
      #   run: |
      #     echo "$KEYSTORE_BASE64" | base64 -d > kidlock.jks
      #   env:
      #     KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      #
      # - name: Assemble Release APK
      #   if: ${{ secrets.KEYSTORE_BASE64 != '' }}
      #   run: |
      #     gradle assembleRelease -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/kidlock.jks       #       -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }}       #       -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }}       #       -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
      #
      # - name: Upload Release APK
      #   if: ${{ secrets.KEYSTORE_BASE64 != '' }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release.apk
      #     path: app/build/outputs/apk/release/app-release.apk
